### ISSUE TITLE
Copy-pasta ?

### ISSUE THREAD

**Issue by codeaye** [mangudaigb/kjr-mathjax-angular#1]
Is there any specific reason why you have cloned our repository and republished it to npm? You couldnt even be bothered to change the readme. If this was regarding support for Angular 14, then thats fine, but just note we have now updated that too! 😁

**Comment by mangudaigb** [comment]
I wanted to try it with angular 14. Happy to use your package if it is updated. :rofl: 
Was planning to link back to you in the next couple of days. Will remove the package no worries.

**Comment by codeaye** [comment]
I see, no worries then 👌
